name: Deploy to SFTP
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER_URL }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY}}
          local_path: './dist/*'
          remote_path: './public_html'
          sftp_only: true
          delete_remote_files: false
